name: Security check - Bandit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v3

    - name: Run bandit
      uses: VCTLabs/bandit-report-artifacts@master
      with:
        project_path: procman
        ignore_failure: false
        exclude_paths: 'procman/examples'
